# Generated by Django 6.0.4 on 2026-05-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productmedia_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_brand_i_5d76ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_is_feat_86dc72_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(choices=[('gm', 'Grams'), ('kg', 'KiloGrams'), ('pc', 'Pieces')], default='gm', max_length=20),
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
