# Generated by Django 6.0.4 on 2026-05-18 05:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_product_pro_brand_i_5d76ed_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thali',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(choices=[('gm', 'Grams'), ('kg', 'KiloGrams'), ('pc', 'Pieces')], default='gm', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thali', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
