# Generated by Django 6.0.4 on 2026-05-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_thali'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_is_acti_9d034c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_categor_2b9d78_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('gm', 'Grams'), ('kg', 'KiloGrams'), ('pc', 'Pieces')], default='gm', max_length=20),
        ),
        migrations.AddField(
            model_name='thali',
            name='quantity_type',
            field=models.CharField(choices=[('gm', 'Grams'), ('kg', 'KiloGrams'), ('pc', 'Pieces')], default='gm', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='thali',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='thali',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='thali',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
