# Generated by Django 6.0.4 on 2026-05-19 05:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_type',
        ),
        migrations.RemoveField(
            model_name='thali',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='thali',
            name='quantity_type',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='quantity_type',
            field=models.CharField(choices=[('gm', 'Grams'), ('kg', 'KiloGrams'), ('pc', 'Pieces')], default='gm', max_length=20),
        ),
        migrations.AddField(
            model_name='thali',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='thali',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='thali',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thali',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thali', to='product.productvariant'),
        ),
    ]
