# Generated by Django 6.0.4 on 2026-05-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productvariant_weight'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productmedia',
            name='unique_primary_product_image',
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('variant',), name='unique_primary_product_image'),
        ),
    ]
