# Generated by Django 6.0.4 on 2026-05-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_productmedia_unique_primary_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='quantity_type',
            field=models.CharField(choices=[('gm', 'Grams'), ('kg', 'KiloGrams'), ('pc', 'Pieces'), ('ml', 'Milliliters')], default='gm', max_length=20),
        ),
    ]
