# Generated by Django 6.0.4 on 2026-05-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productvariant_quantity_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productmedia',
            name='unique_primary_product_image',
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('variant__isnull', True)), fields=('product',), name='unique_primary_product_image'),
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('variant__isnull', False)), fields=('variant',), name='unique_primary_variant_image'),
        ),
    ]
