# Generated by Django 6.0.4 on 2026-05-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_attribute_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_thali_component',
            field=models.BooleanField(default=False),
        ),
    ]
