# Generated by Django 6.0.4 on 2026-06-25 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderitemthalioption_options_and_more'),
        ('product', '0013_productvariant_is_thali_component'),
        ('rating', '0003_alter_rating_created_at_alter_rating_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('product', 'user', 'order')},
        ),
        migrations.AddField(
            model_name='rating',
            name='thali',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='product.thali'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='product.product'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('product', 'user', 'order'), ('thali', 'user', 'order')},
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['thali'], name='rating_rati_thali_i_ba9a64_idx'),
        ),
    ]
