# Generated by Django 6.0.4 on 2026-07-15 12:49

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_id', models.UUIDField(help_text='Product Variant or Thali ID')),
                ('item_type', models.CharField(choices=[('variant', 'Variant'), ('thali', 'Thali')], max_length=10)),
                ('item_label', models.CharField(max_length=255)),
                ('forecast_date', models.DateField()),
                ('predicted_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Demand Forecast',
                'verbose_name_plural': 'Demand Forecasts',
                'ordering': ['item_id', 'forecast_date'],
                'constraints': [models.UniqueConstraint(fields=('item_id', 'forecast_date'), name='unique_item_forecast_date')],
            },
        ),
    ]
