# Generated by Django 6.0.4 on 2026-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_username_delete_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('FARMER', 'Farmer'), ('STAFF', 'Staff')], default='CUSTOMER', max_length=20),
        ),
    ]
