# Generated by Django 6.0.4 on 2026-05-15 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('delivery_type', models.CharField(choices=[('DIRECT', 'Direct from Farmer'), ('WAREHOUSE', 'From Warehouse')], max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in km', max_digits=10, null=True)),
                ('estimated_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
