# Generated by Django 6.0.4 on 2026-05-20 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_delivery'),
        ('product', '0007_mealslot_remove_thali_item_product_product_type_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.useraddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='meal_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='product.mealslot'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
    ]
