# Generated by Django 6.0.4 on 2026-05-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_delivery_address_order_meal_slot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
