# Generated by Django 6.0.4 on 2026-06-03 13:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_delivery_created_at_alter_delivery_updated_at_and_more'),
        ('product', '0013_productvariant_is_thali_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemThaliOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='orderitems',
            name='unique_order_variant',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='thali',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.thali'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='orderitems',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('order', 'variant'), name='unique_order_variant'),
        ),
        migrations.AddField(
            model_name='orderitemthalioption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_thali_options', to='product.thalicomponentoption'),
        ),
        migrations.AddField(
            model_name='orderitemthalioption',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thali_options', to='order.orderitems'),
        ),
    ]
