# Generated by Django 6.0.4 on 2026-06-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitemthalioption_and_more'),
        ('product', '0013_productvariant_is_thali_component'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemthalioption',
            options={'verbose_name': 'Order Item Thali Option', 'verbose_name_plural': 'Order Item Thali Options'},
        ),
        migrations.AlterUniqueTogether(
            name='orderitemthalioption',
            unique_together={('order_item', 'option')},
        ),
    ]
